server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tenant1
#    username: postgres
#    password: root
  flyway:
    enabled: false
tenants:
  datasources:
    tenant_1:
      url: jdbc:postgresql://localhost:5432/tenant1
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver
    tenant_2:
      url: jdbc:postgresql://localhost:5432/tenant2
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver